trigger:
  - master

pool:
  vmImage: 'ubuntu-latest'

variables:
  dockerId: 'metra638'   # замените на ваш Docker Hub ID
  imageName: 'test1'                 # имя образа

steps:
  # Шаг 1: Сборка Docker-образа
  - task: Docker@2
    inputs:
      command: 'build'
      Dockerfile: '**/Dockerfile'
      repository: '$(dockerId)/$(imageName)'
      tags: |
        $(Build.BuildId)
        latest
    displayName: 'Build Docker image'

  # Шаг 2: Логин в Docker Hub (через секретные переменные)
  - script: |
      echo $(dockerPassword) | docker login -u $(dockerId) --password-stdin
    displayName: 'Login to Docker Hub'
    env:
      dockerPassword: $(DOCKER_HUB_PASSWORD)  # секретная переменная

  # Шаг 3: Push образа
  - task: Docker@2
    inputs:
      command: 'push'
      repository: '$(dockerId)/$(imageName)'
      tags: |
        $(Build.BuildId)
        latest
    displayName: 'Push Docker image to Docker Hub'