FROM node:22-bookworm-slim AS base

FROM base AS builder 
WORKDIR /app

COPY FamilyClub.React/famiy.club.react/package*.json ./
RUN npm ci

COPY FamilyClub.React/famiy.club.react/ .

RUN npm run build

FROM base AS runner
RUN apt-get update && apt-get upgrade -y && apt-get clean && rm -rf /var/lib/apt/lists/*
WORKDIR /app

ENV NODE_ENV=production
ENV PORT=3000

COPY --from=builder /app/public ./public
COPY --from=builder /app/.next ./.next
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/package.json ./package.json

EXPOSE 3000

CMD ["npm", "run", "start"]
