# syntax=docker/dockerfile:1

FROM node:22-bookworm-slim@sha256:53ada149d435c38b14476cb57e4a7da73c15595aba79bd6971b547ceb6d018bf AS base

RUN apt-get update && apt-get upgrade -y && apt-get clean && rm -rf /var/lib/apt/lists/*

ARG VERSION
ARG BUILD_DATE
ARG VCS_REF

FROM base AS builder 
WORKDIR /app

COPY FamilyClub.React/famiy.club.react/package*.json ./
RUN npm ci

COPY FamilyClub.React/famiy.club.react/ .

RUN npm run build

FROM base AS runner

LABEL org.opencontainers.image.title="FamilyClub" \
      org.opencontainers.image.description="Frontend FamilyClub" \
      org.opencontainers.image.source="https://github.com/Metra638/FamilyClub.WebAPI1" \
      org.opencontainers.image.version="${VERSION}" \
      org.opencontainers.image.created="${BUILD_DATE}" \
      org.opencontainers.image.revision="${VCS_REF}" \
      maintainer="apofeoz638@gmail.com" \
      environment="production"

WORKDIR /app

ENV NODE_ENV=production
ENV PORT=3000

COPY --link --from=builder /app/public ./public
COPY --link --from=builder /app/.next ./.next
COPY --link --from=builder /app/node_modules ./node_modules
COPY --link --from=builder /app/package.json ./package.json

RUN addgroup --system --gid 1001 nodejs && \
    adduser --system --uid 1001 --gid 1001 nodejs && \
    chown -R nodejs:nodejs /app

USER nodejs

EXPOSE 3000

CMD ["npm", "run", "start"]
