FROM mcr.microsoft.com/dotnet/sdk:10.0-preview AS build
WORKDIR /src
COPY FamilyClub.WebAPI/*.csproj ./FamilyClub.WebAPI/
COPY FamilyClubLibrary/*.csproj ./FamilyClubLibrary/
COPY FamilyClub.BLL/*.csproj ./FamilyClub.BLL/
COPY FamilyClub.DAL/*.csproj ./FamilyClub.DAL/

RUN dotnet restore "./FamilyClub.WebAPI/FamilyClub.WebAPI.csproj"

COPY FamilyClub.WebAPI/ ./FamilyClub.WebAPI/
COPY FamilyClubLibrary/ ./FamilyClubLibrary/
COPY FamilyClub.BLL/ ./FamilyClub.BLL/
COPY FamilyClub.DAL/ ./FamilyClub.DAL/

RUN dotnet publish "./FamilyClub.WebAPI/FamilyClub.WebAPI.csproj" -c Release -o /app/publish --no-restore

FROM mcr.microsoft.com/dotnet/aspnet:10.0-preview AS final
RUN apt-get update && apt-get upgrade -y && apt-get clean && rm -rf /var/lib/apt/lists/*

WORKDIR /app
COPY --from=build /app/publish .

EXPOSE 80
ENTRYPOINT ["dotnet", "FamilyClub.WebAPI.dll"]
