import { categoriesService } from "@/lib/api/services";
import type { Metadata } from "next";
import "../styles/globals.css";
import Link from "next/link";
import Footer from "@/components/layout/Footer";
import { Source_Sans_3, Roboto_Mono } from 'next/font/google';
const sourceSans = Source_Sans_3({
  subsets: ['cyrillic', 'latin'],
  variable: '--font-sans', // Назва CSS змінної для використання шрифту в стилях
});

const robotoMono = Roboto_Mono({
  subsets: ['cyrillic', 'latin'],
  variable: '--font-mono',
});


export const metadata: Metadata = {
  title: "My App",
  description: "Created with Next.js",
};

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  

  return (
    <html lang="en">
      <body className="antialiased bg-background text-foreground font-sans">
        <header className="h-[75px] bg-[#F5F3EE] shadow-sm">
          <div className="h-659px">
            <UpNavigation />
          </div>
      

          {/* <Link href='/categories/all' className="text-primary-action hover:underline">Categories</Link> */}
        </header>

        <main className="p-6 max-w-7xl mx-auto min-h-screen">
          {children}
        </main>

        <Footer />


      </body>      
    </html>
  );
}


















// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "../styles/globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html
//       lang="en"
//       className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
//     >
//       <body className="min-h-full flex flex-col">{children}</body>
//     </html>
//   );
// }
