apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-config
  namespace: kube-system
data:
  fluent-bit.conf: |
    [SERVICE]
        Flush         1
        Log_Level     error
        Daemon        off
        Parsers_File  parsers.conf

    [INPUT]
        Name              tail
        Path              /var/log/containers/*.log,/var/log/pods/*/*.log
        Parser            cri
        Tag               kube.*
        Refresh_Interval  5
        Mem_Buf_Limit     50MB

    [FILTER]
        Name                kubernetes
        Match               kube.*
        Kube_URL            https://kubernetes.default.svc.cluster.local:443
        Kube_Tag_Prefix     kube.var.log.containers.
        Merge_Log           On
        Keep_Log            Off

    [FILTER]
        Name       grep
        Match      kube.*
        Regex      $kubernetes['pod_name'] (familyclub-backend.*|familyclub-frontend.*|familyclub-postgres.*|ingress-nginx-controller.*)

    [FILTER]
        Name       grep
        Match      kube.*
        Exclude    log .*fluent-bit.*

    [OUTPUT]
        Name   stdout
        Match  *